//You are required to print a 'z' of size 5 using '*'.





import java.util.*;
          
          public class Main {
          
              public static void main(String[] args) {
         	         // Write your code here
         System.out.println("*****");
         System.out.println("   * ");
         System.out.println("  *  ");
         System.out.println(" *   ");
         System.out.println("*****");


              }
         }